global:
  workload:
    securityContext:
      fsGroup: null
      runAsUser: null
  externalImage:
    pingtoolkit:
      securityContext:
        runAsUser: null

#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  image:
    name: pingfederate
    tag: 11.3.0-latest
  secretVolumes:
    pingfederate-license:
      items:
        PingFederate-11.3-Development.lic: /opt/in/instance/server/default/conf/pingfederate.lic
  workload:
    type: StatefulSet
  envs:
    SERVER_PROFILE_URL: https://github.com/kshani-collabera/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingfederate
    PING_IDENTITY_ACCEPT_EULA: "YES"
   
#############################################################
# pingfederate-engine values
#############################################################
pingfederate-engine:
  enabled: true
  image:
    name: pingfederate
    tag: 11.3.0-latest
  secretVolumes:
    pingfederate-license:
      items:
        PingFederate-11.3-Development.lic: /opt/in/instance/server/default/conf/pingfederate.lic
  envs:
    SERVER_PROFILE_URL: https://github.com/kshani-collabera/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingfederate
    PING_IDENTITY_ACCEPT_EULA: "YES"

#############################################################
# pingdataconsole values
#############################################################
pingdataconsole:
  enabled: false
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole
    PING_IDENTITY_ACCEPT_EULA: "YES"

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  enabled: false
  image:
    name: pingdirectory
    tag: 2307-9.3.0.0
  secretVolumes:
    pingdirectory-license:
      items:
        PingDirectory-9.3-Development.lic: /opt/in/pd.profile/server-root/pre-setup/PingDirectory.lic
  persistentvolume:
    enabled: true
  container: 
    replicaCount: 3
    volumes:
      name: out-dir
      mountPath: /opt/out
      storage: 8Gi
      storageClassName:
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdirectory
